stages:
  - exe_env_build
  - test_env_build
  - test
  - master_test
  - googlenet_test

exe_env_build:
  stage: exe_env_build
  tags:
    - "shell"
  script:
    - echo "build docker image..."
    - sudo docker build -t biicgitlab.ee.nthu.edu.tw:5050/prod/engineer/fer_offline .
    - echo "docker image has been built"

test_env_build:
  stage: test_env_build
  tags:
    - "shell"
  script:
    - echo "build pytest env..."
    - pip install pytest
    - pip install pytest-html
    - pip install pytest-sugar
    - pip install pytest-icdiff

master_test:
  stage: master_test
  tags:
    - "shell"
  script:
    - echo "pytest..."
    - py.test -vv --html=report.html --self-contained-html --durations=6
    - echo "Finish"
  only:
    - master
  artifacts:
    paths:
      - ./report.html
      
googlenet_test:
  stage: googlenet_test
  tags:
    - "shell"
  script:
    - echo "switch to the branch googlenet"
    - git checkout googlenet
    - echo "pytest..."
    - py.test -vv --html=report.html --self-contained-html --durations=6
    - echo "Finish"
  only:
    - googlenet
  artifacts:
    paths:
      - ./report.html


